export { default as XButton, type XButtonProps } from '@/components/Button.vue'
export { default as XButtonPopconfirm, type XButtonPopconfirmProps } from '@/components/ButtonPopconfirm.vue'
export { default as XConfigProvider } from '@/components/ConfigProvider.vue'
export { default as XDatePicker, type XDatePickerProps } from '@/components/DatePicker.vue'
export { default as XDialog, type XDialogProps } from '@/components/Dialog.vue'
export { default as XForm, type XFormProps } from '@/components/Form.vue'
export { default as XFormItem, type XFormItemProps } from '@/components/FormItem.vue'
export { default as XInput, type XInputProps } from '@/components/Input.vue'
export { default as XInputNumber, type XInputNumberProps } from '@/components/InputNumber.vue'
export { default as XPagination, type XPaginationProps } from '@/components/Pagination.vue'
export { default as XSelect, type XSelectProps } from '@/components/Select.vue'
export { default as XTable, type XTableColumnProps, type XTableProps } from '@/components/Table.vue'
export { default as XTabPane, type XTabPaneProps } from '@/components/TabPane.vue'
export { default as XTabs, type XTabsProps } from '@/components/Tabs.vue'
export { default as XUpload, type XUploadProps } from '@/components/Upload.vue'
