export { default as XButton } from './basic/XButton.vue'
export * from './basic/XButton.vue'
export { default as XCascader } from './basic/XCascader.vue'
export { default as XCheckbox } from './basic/XCheckbox.vue'
export * from './basic/XCheckbox.vue'
export { default as XColorPicker } from './basic/XColorPicker.vue'
export * from './basic/XColorPicker.vue'
export { default as XDatePicker } from './basic/XDatePicker.vue'
export * from './basic/XDatePicker.vue'
export { default as XDialog } from './basic/XDialog.vue'
export * from './basic/XDialog.vue'
export { default as XDivider } from './basic/XDivider.vue'
export * from './basic/XDivider.vue'
export { default as XForm, XFormItem } from './basic/XForm.vue'
export * from './basic/XForm.vue'
export { default as XImage } from './basic/XImage.vue'
export * from './basic/XImage.vue'
export { default as XInput } from './basic/XInput.vue'
export * from './basic/XInput.vue'
export { default as XInputNumber } from './basic/XInputNumber.vue'
export * from './basic/XInputNumber.vue'

export { default as XPagination } from './basic/XPagination.vue'
export * from './basic/XPagination.vue'
export { default as XRate } from './basic/XRate.vue'
export * from './basic/XRate.vue'
export { default as XReconfirm } from './basic/XReconfirm.vue'
export * from './basic/XReconfirm.vue'
export { default as XScrollbar } from './basic/XScrollbar.vue'
export * from './basic/XScrollbar.vue'
export { default as XSelect } from './basic/XSelect.vue'
export * from './basic/XSelect.vue'
export { default as XSpace } from './basic/XSpace.vue'
export * from './basic/XSpace.vue'
export { default as XTable } from './basic/XTable.vue'
export * from './basic/XTable.vue'
export * from './basic/XTabs.vue'
export { default as XTag } from './basic/XTag.vue'
export * from './basic/XTag.vue'
export { default as XText } from './basic/XText.vue'
export * from './basic/XText.vue'
export { default as XUpload } from './basic/XUpload.vue'
export * from './basic/XUpload.vue'
